spring:
  thymeleaf:
    cache: false
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie?characterEncoding=utf-8
    username: root
    password: admin
